import { Task } from '@/types/task';

const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const nextWeek = new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0];

export const mockTasks: Task[] = [
  {
    id: 'task_1',
    propertyId: 'prop_1',
    unitId: 'unit_1',
    propertyName: 'Palm Residency',
    unitNumber: '1.02.25',
    category: 'Cleaning',
    status: 'Assigned',
    priority: 'High',
    description: 'Deep cleaning of the entire apartment including kitchen, bathrooms, living room, and bedrooms. Ensure all surfaces are sanitized and floors are mopped.',
    assignedAt: today,
    dueDate: tomorrow,
    images: [],
  },
  {
    id: 'task_2',
    propertyId: 'prop_1',
    unitId: 'unit_2',
    propertyName: 'Palm Residency',
    unitNumber: '2.05.10',
    category: 'Maintenance',
    status: 'InProgress',
    priority: 'Urgent',
    description: 'Fix leaking faucet in the master bathroom. Tenant reported continuous dripping causing water waste.',
    assignedAt: yesterday,
    dueDate: today,
    images: [],
  },
  {
    id: 'task_3',
    propertyId: 'prop_2',
    unitId: 'unit_3',
    propertyName: 'Al Raha Gardens',
    unitNumber: '3.01.08',
    category: 'Inspection',
    status: 'Completed',
    priority: 'Medium',
    description: 'Routine quarterly inspection of all electrical outlets, smoke detectors, and fire extinguishers.',
    assignedAt: yesterday,
    dueDate: yesterday,
    completedAt: yesterday,
    images: ['/placeholder.svg'],
  },
  {
    id: 'task_4',
    propertyId: 'prop_2',
    unitId: 'unit_4',
    propertyName: 'Al Raha Gardens',
    unitNumber: '1.03.15',
    category: 'Cleaning',
    status: 'Assigned',
    priority: 'Medium',
    description: 'Standard checkout cleaning. Previous tenant has vacated. Prepare unit for next guest arrival.',
    assignedAt: today,
    dueDate: tomorrow,
    images: [],
  },
  {
    id: 'task_5',
    propertyId: 'prop_3',
    unitId: 'unit_5',
    propertyName: 'Marina Heights',
    unitNumber: '5.12.01',
    category: 'Maintenance',
    status: 'Assigned',
    priority: 'Low',
    description: 'Replace light bulbs in hallway and balcony. Use warm white LED bulbs as per building standards.',
    assignedAt: today,
    dueDate: nextWeek,
    images: [],
  },
  {
    id: 'task_6',
    propertyId: 'prop_3',
    unitId: 'unit_6',
    propertyName: 'Marina Heights',
    unitNumber: '2.08.03',
    category: 'Cleaning',
    status: 'InProgress',
    priority: 'High',
    description: 'Post-renovation deep clean. Remove all construction dust, clean windows inside and out, polish all surfaces.',
    assignedAt: yesterday,
    dueDate: today,
    images: [],
  },
  {
    id: 'task_7',
    propertyId: 'prop_4',
    unitId: 'unit_7',
    propertyName: 'Saadiyat Villas',
    unitNumber: 'V-14',
    category: 'Inspection',
    status: 'Assigned',
    priority: 'Medium',
    description: 'Pre-move-in inspection. Check all appliances, plumbing, HVAC system, and document any existing damage.',
    assignedAt: today,
    dueDate: tomorrow,
    images: [],
  },
  {
    id: 'task_8',
    propertyId: 'prop_4',
    unitId: 'unit_8',
    propertyName: 'Saadiyat Villas',
    unitNumber: 'V-22',
    category: 'Maintenance',
    status: 'Completed',
    priority: 'High',
    description: 'AC unit servicing and filter replacement. System was not cooling efficiently.',
    assignedAt: yesterday,
    dueDate: yesterday,
    completedAt: yesterday,
    images: ['/placeholder.svg'],
  },
];
